import { Product } from '../../ui/interfaces';

const GET_PRODUCTS_SUCCESS: string = 'GET_PRODUCTS_SUCCESS';
const GET_PRODUCTS_REQUEST: string = 'GET_PRODUCTS_REQUEST';
const GET_PRODUCTS_FAILURE: string = 'GET_PRODUCTS_FAILURE';

const SELL_PRODUCT_REQUEST: string = 'SELL_PRODUCT_REQUEST';
const SELL_PRODUCT_SUCCESS: string = 'SELL_PRODUCT_SUCCESS';
const SELL_PRODUCT_FAILURE: string = 'SELL_PRODUCT_FAILURE';

const DELETE_PRODUCT_REQUEST: string = 'DELETE_PRODUCT_REQUEST';
const DELETE_PRODUCT_SUCCESS: string = 'DELETE_PRODUCT_SUCCESS';
const DELETE_PRODUCT_FAILURE: string = 'DELETE_PRODUCT_FAILURE';

export const types = {
  GET_PRODUCTS_REQUEST,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_FAILURE,
  SELL_PRODUCT_REQUEST,
  SELL_PRODUCT_SUCCESS,
  SELL_PRODUCT_FAILURE,
  DELETE_PRODUCT_REQUEST,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_FAILURE,
};

export interface GetProductsSuccess {
  type: typeof GET_PRODUCTS_SUCCESS;
  payload: Array<Product>;
}
